### ISSUE TITLE
Add better support for vanilla items

### ISSUE THREAD

**Issue by goflishMC** [magemonkeystudio/fusion#23]
The visual in menus does not look good when using vanilla items.

**Comment by MaksyKun** [comment]
Just some stuff that came in my mind too:
- Allow specific enchantment books to be used with desired enchantment + level (and also multiple on a book)
- Allow for vanilla-items with specific item-meta (enchantments, flags, etc.)

### View of enchantment books
Something like:
- Enchanted Book
  -> Efficiency 5

### View of specific item-meta
- Stone Block
  - Ench: Efficiency 3
  - Ench: Unbreaking 3
  - Unbreakable
  - HideFlag: <...>


It would maybe make sense to make a seperated config file to customize this stuff with full potential
