### ISSUE TITLE
Add example professions and recipes on fresh install

### ISSUE THREAD

**Issue by goflishMC** [magemonkeystudio/fusion#27]
Add a couple professions with recipes.

One profession should have a couple categories to demonstrate how categories work.

This would add a few items to prorpgitems to be used in the example on the first install.

**Comment by Kyles1201** [comment]
please my friend help me and do this... i am indian and can not figure out how to make anything... please help me sir i am indian sir.

**Comment by goflishMC** [comment]
> please my friend help me and do this... i am indian and can not figure out how to make anything... please help me sir i am indian sir.

we decided to make an in game editor for this to simplify the process
